### PR TITLE
Code to simulate VM placement groups with traces from real DCs (WIP)

### PR DESCRIPTION
**Pull request by ppmaniotis**
This PR introduces 28 new source code files organized in 6 new packages (see list at the end of this message). The code was originally developed to support the work published in [1]-[3]. 

The majority of the development was realized on top of a local copy of CloudSim Plus 6.2.2. The code was recently ported to a fork of the main branch (following the release of version 7.3.2) in order to contribute it back to the original project. Regarding the existing code base, minor edits/additions have been made to (a) VmAllocationPolicyAbstract, (b) CloudSimTag, (c) HostSuitability, (d) DatacenterBrokerAbstract, and (e) HostSimple. Edits in items (a), (b), and (c) are probably safer to adopt, while edits in items (d) and (e) were made in order to make the code runnable again with version 7.3.2. Therefore, more attention is required before accepting these changes since further work may be needed. All files are coming with detailed doxygen documentation.

This PR is submitted together with PR [#11](https://github.com/cloudsimplus/cloudsimplus-examples/pull/11).

Please contact me if there are any questions or help is needed with tidying up any parts the code. Thanks! 

References:  
1) P. Maniotis, L. Schares, D. M. Kuchta and B. Karacali, "Improving Data Center Network Locality w/ Co-packaged Optics," 2021 European Conference on Optical Communication (ECOC), 2021, pp. 1-4, doi: 10.1109/ECOC52684.2021.9606112.
2) P. Maniotis, L. Schares, D. M. Kuchta and B. Karacali, "Toward higher-radix switches with co-packaged optics for improved network locality in data center and HPC networks [Invited]," in Journal of Optical Communications and Networking, vol. 14, no. 6, pp. C1-C10, June 2022, doi: 10.1364/JOCN.451449.
3) Laurent Schares, Asser Tantawi, Pavlos Maniotis, Ming-Hung Chen, Claudia Misale, Seetharami Seelam, Hao Yu, "Chic-sched: a HPC Placement-Group Scheduler on Hierarchical Topologies with Constraints," 37th IEEE International Parallel & Distributed Processing Symposium (IPDPS 2023), St. Petersburg, Florida, USA, May 15-19, 2023

New packages:
1) org.cloudbus.cloudsim.allocationpolicies.vmplacementgroups: 8 files
2) org.cloudbus.cloudsim.resources.utilization: 2 files
3) org.cloudbus.cloudsim.vms.vmplacementgroup: 5 files
4) org.cloudsimplus.builders.tables.vmstatistics: 3 files
5) org.cloudsimplus.traces.azure: 7 files
6) org.cloudsimplus.traces.vmallocationpolicywithgroups: 3 files

### CODE REVIEW

**Comment by jlxcsong** [comment]
您好！您发的邮件我已收到！

**Comment by manoelcampos** [comment]
Hello @ppmaniotis 

First of all, thanks for your interest in CloudSim Plus and your contribution.
The project really needs collaborators and contributions are always welcome.
However, I have many concerns about this PR and I don't know if you are interested and have the time to work on it.

Please don't get me wrong. The features you've implemented are great, mainly the support for Azure traces.
The number of changes in the framework code is small, which is appreciated.
But there are major issues that need to be addressed in order to marge this PR.
I have just passed through the code. If you have the time and interest to work on required changes, I'll perform other review rounds. I'l pointing out some issues I've found in this initial review:

- Code duplication in CloudSim is one of the main reasons that made me create CloudSim Plus. If you check the CloudSim Plus paper at the project home page, you'll see how that was a major concern. I see many duplicated code in this PR that needs to avoided by using proper engineering. 
- The support for Azure traces is great and this is highly requested feature, but that support must be created based on the existing abstract classes such as TraceReaderAbstract.
- Azure have so many different trace files and versions. A more defailed documentation is required in order to make it clear which files and versions are supported. You can see that the Google Cluster Trace have a more detailed documentation compared to other classes.
- There are some coupling issues in the code. For instance, the VmAllocationPolicyBestFitWithPlacementGroups depends on a TracesSimulationManager, which is a class for the Azure traces implementation. VmAllocationPolicy must be independent of any data source.

Please let me know if we can work toghether to fix these issues that I start a complete review.

**Comment by manoelcampos** [comment]
I've just merged the latest changes in the dev branch into your branch.

**Comment by manoelcampos** [comment]
I'm releasing CloudSim Plus 8.0 in the next days.
This is a major refactoring release that breaks compatibility with previous versions.
The major changes are the inclusion of [Lombok](http://projectlombok.org) and packages restructuring,
moving away from `org.cloudbus.cloudsim` entirely to `org.cloudsimplus` since the two frameworks are internally very different after almost 10 years.

There are large structural changes and I've performed a rebase to put your branch on top of the changes in the dev branch. This way, your branch is ready to work with CloudSim Plus 8.0.

Please let me know if you have issues updating your local branch before making changes.

**Pull request closed without merging**
